// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saiatfvyvyrhgkntxorh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhaWF0ZnZ5dnlyaGdrbnR4b3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMTE5MDQsImV4cCI6MjA3NTU4NzkwNH0.Oa2Q3SeXSAyKx7kJcvCWJ8VIN2DUVZohfMC_IngvHC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});